DataSource:
  USERNAME: root # 用户名
  PASSWORD: AES@6b5c41aa0669b5c476e19720eae7b8ed # 密码
  HOST: 106.14.220.77 # 数据库地址
  PORT: 3306 # 端口
  DATABASE: health # 数据库名
  PARAM: charset=utf8  #服务器连接参数

Redis:
  HOST: 172.96.229.205 #redis地址
  PORT: 16379 #端口
  PASSWORD: 123456 #密码
  DB: 8 #数据库
  EXPIRE_TIME: 60 # 过期时间
  TIMEOUT: 300 # 连接超时