LANG: zh_CN

DataSource:
  USERNAME: root # 用户名
  PASSWORD: AES@6b5c41aa0669b5c476e19720eae7b8ed # 密码
  HOST: 106.14.220.77 # 数据库地址
  PORT: 3306 # 端口
  DATABASE: health # 数据库名
  PARAM: charset=utf8  #服务器连接参数

Redis:
  HOST: 192.168.174.128 #redis地址
  PORT: 6379 #端口
  PASSWORD: 123456 #密码
  DB: 8 #数据库

Scheduler:
  ENABLE: True
  THREADPOOL: 20
  MAX_INSTANCES: 3