LANG: zh_CN

DataSource:
  USERNAME: root # 用户名
  PASSWORD: AES@6b5c41aa0669b5c476e19720eae7b8ed # 密码
  HOST: * # 数据库地址
  PORT: * # 端口
  DATABASE: technology_online # 数据库名
  PARAM: charset=utf8  #服务器连接参数

