LANG: zh_CN

DataSource:
  USERNAME: root # 用户名
  PASSWORD: * # 密码
  HOST: * # 数据库地址
  PORT: * # 端口
  DATABASE: health # 数据库名
  PARAM: charset=utf8  #服务器连接参数

Redis:
  HOST: * #redis地址
  PORT: * #端口
  DB: * #数据库

Scheduler:
  ENABLE: True
  THREADPOOL: 20
  MAX_INSTANCES: 3